spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newdb
    username: developer
    password: developer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
    driver-class-name:  org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled: true